# Generated by Django 5.0.6 on 2026-06-15 16:08

import django.db.models.deletion
import django.utils.timezone
import shipments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_token', models.CharField(db_index=True, default=shipments.models.generate_tracking_token, editable=False, max_length=16, unique=True, verbose_name='Tracking Token')),
                ('package_description', models.TextField(verbose_name='Package Description')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Declared Value')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Length (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Width (cm)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Height (cm)')),
                ('service_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Reference')),
                ('destination_country', models.CharField(max_length=100, verbose_name='Destination Country')),
                ('current_status', models.CharField(choices=[('registered', 'Registered'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('customs', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned to Sender'), ('on_hold', 'On Hold')], db_index=True, default='registered', max_length=30, verbose_name='Current Status')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Location')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid')], default='unpaid', max_length=20, verbose_name='Payment Status')),
                ('estimated_delivery_at', models.DateTimeField(verbose_name='Estimated Delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shipments.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Sender',
                'verbose_name_plural': 'Senders',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shipments.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Receiver',
                'verbose_name_plural': 'Receivers',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('customs', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned to Sender'), ('on_hold', 'On Hold')], max_length=30, verbose_name='Status')),
                ('location_description', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipments.shipment', verbose_name='Shipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_token'], name='shipments_s_trackin_fb782d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['current_status'], name='shipments_s_current_c1528d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['destination_country'], name='shipments_s_destina_f61249_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['-created_at'], name='shipments_s_created_d16103_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['payment_status'], name='shipments_s_payment_4b6da5_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['shipment', '-event_timestamp'], name='shipments_t_shipmen_540a86_idx'),
        ),
    ]
